apiVersion: v1
kind: Secret
metadata:
    name: gitea-runner-secret
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:37Huh9DuCpE2WpzU/8tgCNkHtGDUXbZ1UkjCpvHCm7tSDLmtfXTkhQ==,iv:19T3to4S9DSIBMstryT3+MgFjfoXr+jMToLV4lIW+Lc=,tag:02RTnoDTx2DNrcXDFWp9kg==,type:str]
sops:
    age:
        - recipient: age1s0gmt47hc9fktm9juqafyp5s0ptnsc933cg0wwq3x5e83ehk0pzq06u9qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZkUrY20welFic3FpdWtv
            NndMTXJFa0hRMVRtMzFuZ0tZMVNlRFZpNldvCmlaejNRdkZnNkdkWmVmcXdGRjJj
            eHNoeDNTNnp4VTFjSXVJeXdxNGVockEKLS0tIERSSng3OUhod1lTMUxXZUltQm5D
            OEdaQUMwWkJMYWh4MDhqWDRzZzNlMmcKpmKU+mNMGJi/6rx8yahn4vfmIOyS7PQo
            O3ZzpdJtMnYMOX4+Eost5hHuVQonQg51lts7bhx/2xOgYaUSDRcaeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T12:06:28Z"
    mac: ENC[AES256_GCM,data:BaQEPmFynBamoTwRt5Srb2Q5/GNXNO0nZ6P4+e6OXhnIpPGlcdNk9Mzo+FLOEj4CcTQwFIBnX/Ju78svwooSeSNgNc5Vm7T+3tKtgdFHDDwAC7NP2RlTgofmCaCHZJc0HQvoJlhSASK4U9AqHum7rme8WeJBl22VFUrAxjezhls=,iv:+AojUZNI1V0qP2W4VxvIzhcbQwpmtqSSdJlvZr92anI=,tag:oDZswbW5vpNvG0gi8TXLNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
