apiVersion: v1
kind: Secret
metadata:
    name: gitea-runner-secret
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:cHZ/+2qHW0DB3t+sW73f3TTj2HCUEyVHKvSO8l0jOxxHOZ0vw8clkg==,iv:dAOP7wCa7ta3sjcTfj0hq0DbscjUO0C6NOov+TyWZAg=,tag:5xT6UjINpLb4CKRoG7Qw3w==,type:str]
sops:
    age:
        - recipient: age1s0gmt47hc9fktm9juqafyp5s0ptnsc933cg0wwq3x5e83ehk0pzq06u9qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y3cvVWtnRHJ6cjJ4a3JK
            Rmppd0trMHdHMWZLMkdRQnMxL2JrMWcrWldFCjNlOGpHWWlGSVJ1VlozZmp2TjdB
            eDRVQW9GVld6RS9qenhKUkNDbDcybWsKLS0tIHRFTFN0STV4WVNFL2pURm5TT29m
            NEVUWkJNZHIrdkpxL09GQ2dENVo4RDAK0kcrEw9mxDfS/oxBFF1/z6XStX1GGzmH
            KRyhovuQ92NalEJSjD4Pl0l8AVpmJxOqTyLZZ4p4ircecqbVwJnMYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T12:08:26Z"
    mac: ENC[AES256_GCM,data:aDrfYVb977kShBzNJJ4OQEsGlrIMnn/Hfnrwg4Evh4KyR2TOlMRBwnWNb+f2s77iIrDRWDN0hNoHn1eX+ihKIVxifc8NJL/aleJmPf6fhVj4jsobtnGtxmer8/ujizBoHRTcGbCFa5OV014l08TH5xBXl1TfLydY+PlMlsQYvq0=,iv:vnXan5E3hrhVEYyrC8fddRPy58FpPeiZM6NReIMZZrE=,tag:J7miojkFZY7C8gUZVsbM4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
