apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ZBBu93yDHahgNgpRZhUlcOMSLubNciOIejnI37SgZ49xNv53c7+VDrOHO1Al8ZujKe+du/7vT04XzNQXwgTUBOVgfabSAfxVs03LJQzmusWrE6iWQs0HYEogF1QHGWu8qirW6ZuWn1qyvFgV84xvkar57roW0EMo6WUAmcGTgfrVykvMUnGIrTOtSx3GtjLSXCKBR26zb+LGm1R1qXXZBNWP7fYhgOVd+qpLRRx0mEIesA39,iv:QZKmrMfRc1UBFILwRcQ3Qy+w8T05aZZ+jy5x2Fxppy0=,tag:f/sTqnSmwdxzw/utd8aW8g==,type:str]
sops:
    age:
        - recipient: age1s0gmt47hc9fktm9juqafyp5s0ptnsc933cg0wwq3x5e83ehk0pzq06u9qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VE5yanM4QTBPNDRxZEdW
            V0gxUjdna1pvbWJDL1pYMFYzOXc0UUhDZjNRCnBrNklITlhTM3hxUHVqWFJDM0lS
            cmwvZHpDcnl2VWNtOGlHUzMxNmtvM2MKLS0tIGRFOUpQRlAzWEp1YmJRNlEwQk1q
            QVpVOHB0TEFoTm5QL2NJUzZYMVhxSXcKByq2zr79nWhzf4UEEyJPVwFgtBOLVwAE
            wAW3QIJQ9oHa/h5P5++Zg4qLsRQBXsYIvotas2QjD4quXFmnrBjXew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T12:06:28Z"
    mac: ENC[AES256_GCM,data:x7jXOIn+3Ux7UMt2iQui/ihpBYjaiKE8d8mBc8j9H8QGJ1abTNRDuI4bNJabu0yZhMZnnubQ/42x8kODUq8s2DXfU1NWkrRzJbsl1F9Qa9U53zeNOfGc+vqFenydhC1tQbGmM3FKciz/vkpBNeer/9WawFh5iAJRAHD74CnD/JQ=,iv:Rs01AzuNItzvNEn3M//OkEYxl/s25i3vzL9DfS4uSJY=,tag:WwVltglzkrPJbggYrGBxyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
