apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IBngnut2My9y0LwR+2HiaKeZ3dBNqGtwT8xePqsjoQTpiNlpbGIfzAKpbvaCCRocU0Wm5bUR61oyWP/cgfVNlrtVs+5jKmqQt++8rIwCu5B/kXp74WSis9CMOZo+M8bf4uw/tLJh1apDePDP5aDY40xHXo5fyVJI9/8SGzvbAI2p3iGIy4nNGfwKD1qlGQpbvIS8/SWhbbpwDU9ol6lwE6wssbbxyqkKqvZ2vTD08PZgRN9h,iv:e2l3+7tAELx7HFWW7Px/OZ8XUGLVOiCJUSKjVtVQDJA=,tag:0RyVLB4CLpqq2Qy6IhHlQA==,type:str]
sops:
    age:
        - recipient: age1s0gmt47hc9fktm9juqafyp5s0ptnsc933cg0wwq3x5e83ehk0pzq06u9qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR0VCSEMxWHdlOWNqRnky
            L3JMOFM3RGNEUFFFa2JEb1o5bDZXUWFQSERNCkpxY0VYMXhmNjlHVTFYMzd3Mk9W
            RmRpbmdueW5vMGIxajlzWUZleEEwZkUKLS0tIDAyTWNUVnRKZjhEUjlCQmZHaEVQ
            TG1uMHVDVFE4eTJlWVlITWtQeHZjZjAKhIn/RJvwUEi5hVznAfXqgDbKptWO0pBw
            H57BwCDGdKsp+VofKer4fVn1ktLLt0tCY1EL0/uGzCPKmVtH7OU61Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T10:32:57Z"
    mac: ENC[AES256_GCM,data:evPciqte+wJEmBhRiXxH2BGdZsNZ6aVySmUaebSgDTgpamLpeHT6nZwxxBe4W4nJKr9mYcSDrdrmKV1ifhq80sGQkejU1w7/f1j/yM+K8b3ZqYUtUNGHptwNJEer4rQh3UdJF6/0pe3dpjLHFN5KaFuNfbrcEOfopSJXxnEXSzQ=,iv:yDjpSBBqJqlrRVUK0OFquZFurT0QkTS97gG54PczdVs=,tag:d2wVm32e5kDlj5nW4TRDsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
