apiVersion: v1
kind: Secret
metadata:
    name: restic-secret
    namespace: default
type: Opaque
stringData:
    b2-key-id: ENC[AES256_GCM,data:hz8+43Dyo1KafIhkMX4DL0GmDS/aYwpvhA==,iv:0EYvW2DMpTAg8+1zMyeVW+IsHUxcUL2JIBs4DBdHcNo=,tag:CsA0xeOwHWZMvuSaPqWE7A==,type:str]
    b2-app-key: ENC[AES256_GCM,data:dCzG+PLRcpDtJ23jXjLJvvtiSD30Uv2hAZFdIzwC/A==,iv:ZHnek+BTDpUoDe2GGQb1DZnQGaDxYa2LJsjgE5JRXaI=,tag:aJMV7UiZ9K9HnEcI3gB86w==,type:str]
    restic-password: ENC[AES256_GCM,data:y5sPqJ/XvMIGenVLWT7nODH8ChGS+5YBACzfl4WT4chh03oQKBWIM7E/sVs=,iv:C6lX9Z+ocWZFR7h8Ctppc7z5rTMSZIpdbYYhx2+J0fY=,tag:yZLkMO9otnqPlANC2Xe2OQ==,type:str]
    repository: ENC[AES256_GCM,data:az74z/pYjAvb8CizjYDOCnlf9gdKsFVkysOM+M9FkTpqOd+iZgLImrA8lUzcw29rmca73J+XMOFATgrn2OiW5oH9Kg==,iv:Og2EJIEHvMt+FMXEk9Nchkb/iz1dxIxVPPgGmI/okMY=,tag:9kWmmPkkukre5H5PwMwjpw==,type:str]
sops:
    age:
        - recipient: age1s0gmt47hc9fktm9juqafyp5s0ptnsc933cg0wwq3x5e83ehk0pzq06u9qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMzlpTWNvNTRJUUpZVG1G
            bnN5b1JscmwzWlZmajRtejJYMGcwalZJNGh3Cmt3Q21TSXozdDl3NkpGbk02S04x
            TDdVSXFZdzV5TW9jQTJKdUo1Sk43RTQKLS0tIDIybGxtOXZGd2owQUgwRy9jamtX
            K0hod2tRRnNuK2VpN015RE5Gbk1RMnMKx8thiVBM6MCvbE65g29KKzWiGHiJizDB
            kBYKq7/9zRoMUEWTpLH+zOh6YwiuUly56vCLwB5719LbZaEGEyQJNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T12:15:51Z"
    mac: ENC[AES256_GCM,data:a1s/wJa6X83ti52uIKoFkbBYIUeKj3iS1Sf1sIaLqxCN0ciTaV2R6qnhHTJVd6ZMqIfborQCHV9rAg0W8e63q2MiGBLO9dJvzjRgt3ZgrYSoI2l+gdyrQBSHG9DBcfrPJOYWxeu3Eu1tI9ROR7wRp9PSWPjaOEpj6h4rzm73JH0=,iv:X9VhAntWr7njoWbAtz6MKrE2xUM2S32KaYx0P9Gkivc=,tag:hvb5LOgfWl1xwhclUIoI0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
